---
title: "mapping"
author: "Dahn-Young Dong"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(rgdal)
library(rnaturalearth)
library(GISTools)
library(mapplots)
library(sp)

create_dir(c("./Results_Maps"))
```

#------------------------------------------------------------------------------
#                    1. Loading Files and Configuring Maps 
#------------------------------------------------------------------------------

```{r}
###1.2. LOAD VCF FILES, GEOGRAPHICAL INFORMATIONS AND ADMIXTURE COEFFICIENTS: 
#A. Load neutral .vcf file with geographical information and admixture and :
snps_neutral = vcfLink(paste0("vcf/", project_name, "_filtered_neutral_LEA_DAPC_TESS.vcf"), overwriteID=T)
VCFsummary(snps_neutral) #16 individuals and 100 SNPs.

#B. Create a data frame with the information on metafile
df = as.data.frame(snps_neutral@meta)
head(df)
tail(df)

#E. Create vectors with samples' position by population in TESS approach:
for (i in 1:length(unique(df$PopID_tess))){
  pop = which(df$PopID_tess == i)
  assign(paste0("pop_TESS_", i), pop)
}

```

```{r}
###1.3. DEFINE A EXTENSION FOR THE MAPS
#A. Calculate the range for the geographical coordinates:
long_extension = c(min(df$longitude), max(df$longitude))
lat_extension = c(min(df$latitude), max(df$latitude))
#verify the range of coordenates
long_extension
lat_extension

#B. Plot points for samples 
plot(snps_neutral@meta$longitude, snps_neutral@meta$latitude)

#C. Choose a extension for maps that cover all points. In this case:
ext = extent(-72.16100, -72.11800, 41.91700, 41.97200)

#D. Define the axes from maps
axis.x = c(-72.16100, -72.11800)
axis.y = c(41.91700, 41.97200)
```

###1.4. CREATING RASTER FOR THE BASE OF MAPS - ELEVATION
```{r eval=FALSE, include=FALSE}
#A. Load DEM raster (elevation raster):
#DEM = elevationLow <- readRDS("./maps/rasters/elevation.rds") ## extent didn't match so skip for now 
#DEM <- projectRaster(DEM, crs = landcover@crs)
#plot the map
#plot(DEM, col = gray.colors(20, start = 0, end = 1))
#crop according to study area
#DEM_base = crop(DEM, ext)

#temp <- raster::readAll(DEM_base)
#saveRDS(temp, file = "./maps/rasters/DEM_base.rds")

DEM_base <- readRDS("./maps/rasters/DEM_base.rds")
plot(DEM_base, col = gray.colors(20, start = 0, end = 1))
```

#------------------------------------------------------------------------------
#                           2. Mapping Genetic Clusters 
#------------------------------------------------------------------------------
```{r}
###2.3. MAPS USING TESS POPULATIONS
#A. Open pdf, choose the font letters, margins and axes.
pdf(paste0("./Results_Maps/Map_TESS_pops_", project_name, ".pdf"), family="Helvetica", onefile = F)
#set parameters
plot.new()
# Add margins
par(oma=c(2,2,2,2))
# Add axis
plot.window(xlim= axis.x, ylim= axis.y)
```

```{r}
#B. Plot maps for the base
plot(DEM_base, col = gray.colors(20, start = 0, end = 1), ext = ext)
#points(snps_neutral@meta$longitude, snps_neutral@meta$latitude)

#C. Plot lat and long axes:
#axis(1, at=seq(-72.16100, -72.11800, by=0.01))
#axis(2, at=seq(41.91700, 41.97200, by=0.01))

#D. Plot the points:
#set population names and colors. SAME THAN STEP 2!
col_tess= c("red","orange","yellow","green","blue","purple","black","grey","turquoise") 
legend_tess = c("POP1", "POP2", "POP3", "POP4", "POP5", "POP6","POP7","POP8","POP9")

#plot points. One line for each populations. Add or remove lines according to your necessity. #the code here is inconsistent, can't find pop_TESS_X
points(df$longitude[pop_TESS_1], df$latitude[pop_TESS_1], col = 'black', bg = col_tess[1], cex = 2.5, pch=21) #POP1
points(df$longitude[pop_TESS_2], df$latitude[pop_TESS_2], col = 'black', bg = col_tess[2], cex = 2.5, pch=21) #POP2
points(df$longitude[pop_TESS_3], df$latitude[pop_TESS_3], col = 'black', bg = col_tess[3], cex = 2.5, pch=21) #POP3
points(df$longitude[pop_TESS_4], df$latitude[pop_TESS_4], col = 'black', bg = col_tess[4], cex = 2.5, pch=21) #POP4
points(df$longitude[pop_TESS_5], df$latitude[pop_TESS_5], col = 'black', bg = col_tess[5], cex = 2.5, pch=21) #POP5
points(df$longitude[pop_TESS_6], df$latitude[pop_TESS_6], col = 'black', bg = col_tess[6], cex = 2.5, pch=21) #POP5
points(df$longitude[pop_TESS_7], df$latitude[pop_TESS_7], col = 'black', bg = col_tess[7], cex = 2.5, pch=21) #POP5
points(df$longitude[pop_TESS_8], df$latitude[pop_TESS_8], col = 'black', bg = col_tess[8], cex = 2.5, pch=21) #POP5
points(df$longitude[pop_TESS_9], df$latitude[pop_TESS_9], col = 'black', bg = col_tess[9], cex = 2.5, pch=21) #POP5
```