---
title: "Minimum viable analysis"
author: "Dahn-Young Dong"
date: "10/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mimimum Viable Analysis

Follow the scripts from https://github.com/jdalapicolla/LanGen_pipeline_version2, the ones related to manipulating and visualizing genetic data given spatial coordintaes


### load package if needed
```{r}
#require(gstudio)
```

### Follow LandGen Pipeline

```{r}
# THE FILE ".CSV" WITH THE GEOGRAPHICAL INFORMATION OF GENETIC SAMPLES IN DECIMALS DEGREES PREFERENCIALLY AND ONE COLUMN WITH LOCALITIES IDs. DIFFERENT INDIVIDUALS MUST HAVE DIFFERENT COORDINATES. IF TWO OR MORE SAMPLES WERE COLLECTED IN THE SAME LOCALITY, CHANGE THE VALUE OF 4TH OR 5TH DECIMAL NUMBER TO SET A DIFFERENCE OF 1 OR 5 METERS. SOME ANALYSES COULD RETURN ERRORS IF THE DIFFERENCES IN METERS BETWEEN INDIVIDUALS IS 0. -- somehow jitter the last digits
name_longlat <- read.csv("coords/YMF2018_RASYpopgen_sampleinfo.csv", as.is = TRUE)[,c(1:2,6,13:14)]

#shuffle column names to include trim name that match to name_longlat "extract" elements
```


```{r}
#import
pilot.loci <- pegas::read.vcf("./input/rasy_ymf_main.vcf", from = 10000, to = 10999)
```

### PhyloNet- to build a consensus introgression tree, if the populations evolve tree-like at all
